### ISSUE TITLE
BTLE example

### ISSUE THREAD

**Issue by roryee** [ApparentlyConnected/Energia-Storm-Ninja-Dist#2]
The LED1 and LED2 variables are never defined.

**Comment by nathancrum** [comment]
They are defined as part of the Storm Ninja wiring in pins_energia.h in the variants folder:
https://github.com/ApparentlyConnected/Energia-Storm-Ninja-Dist/blob/master/energia-0101E0014/hardware/msp430/variants/storm_ninja_p2/pins_energia.h

**Comment by roryee** [comment]
Which is not included in the BTLE_RN4020 example.

**Comment by plmarcus** [comment]
It should be included automatically in the background.

**Comment by roryee** [comment]
Oh, yeah, never mind. Energia reset the board when I restarted it.
